name: wpfamilylastseen
description: A Whatsapp Viewer App.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  iconify_flutter: ^0.0.5
  flag: ^6.0.0
  fluttertoast: ^8.1.1
  url_launcher: ^6.1.6
  fl_chart: ^0.55.2
  country_pickers: ^2.0.0
  intl: ^0.17.0
  provider: ^6.0.4
  country_codes: ^2.2.0
  language_picker: ^0.4.1
  http: ^0.13.5
  device_information: ^0.0.4
  timezone: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/launcher_icon.png"
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/launcher_icon.png"
    icon_size: 48

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - lib/json/
